# Generated by Django 3.2.16 on 2024-04-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='О компании')),
            ],
            options={
                'verbose_name': 'компании',
                'verbose_name_plural': 'О компании',
            },
        ),
    ]
