# Generated by Django 3.2.16 on 2024-04-16 14:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='О компании')),
                ('photo', models.ImageField(upload_to='images/about')),
            ],
            options={
                'verbose_name': 'компании',
                'verbose_name_plural': 'О компании',
            },
        ),
    ]
