# Generated by Django 3.2.16 on 2024-04-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='Default Title', max_length=256),
            preserve_default=False,
        ),
    ]
