# Generated by Django 3.2.16 on 2024-04-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О компании', 'verbose_name_plural': 'О компании'},
        ),
        migrations.AlterField(
            model_name='about',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='about', verbose_name='photo'),
        ),
    ]
