# Generated by Django 3.2.16 on 2024-04-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20240416_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть публикацию.', verbose_name='Опубликовано'),
        ),
    ]
