# Generated by Django 3.2.16 on 2024-04-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_about_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(help_text='Данный заголовок преднозначен для личного понимания', max_length=256, verbose_name='Заголовок'),
        ),
    ]
