# Generated by Django 3.2.16 on 2024-04-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curse',
            name='description_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
    ]
