# Generated by Django 3.2.16 on 2024-04-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0002_curse_description_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='curse',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='curse', verbose_name='Фотография'),
        ),
    ]
