# Generated by Django 3.2.16 on 2024-04-18 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0003_auto_20240418_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curses.location', verbose_name='Адрес'),
        ),
    ]
