# Generated by Django 3.2.16 on 2024-04-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0004_alter_timetable_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Адрес'),
        ),
    ]
