# Generated by Django 3.2.16 on 2024-04-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0008_timetable_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_up_for_a_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=256, verbose_name='Емаил')),
                ('curse', models.CharField(max_length=256, verbose_name='Курс')),
                ('call_back', models.BooleanField(default=True, help_text='Клиент попросил перезвонить позже.', verbose_name='Перезвонить')),
                ('is_delete', models.BooleanField(default=True, help_text='Клиент попросил больше не звонить.', verbose_name='Удалить')),
                ('is_sign_up', models.BooleanField(default=True, help_text='Готов придти на курс.', verbose_name='Придет на курс')),
            ],
            options={
                'verbose_name': 'Заявки послупления на курс',
                'verbose_name_plural': 'Заявки послупления на курс',
            },
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='address',
        ),
    ]
