# Generated by Django 3.2.16 on 2024-04-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0010_auto_20240418_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_up_for_a_course',
            name='customer_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий клиента'),
        ),
    ]
