# Generated by Django 3.2.16 on 2024-04-18 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0012_sign_up_for_a_course_authors_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть публикацию.', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos_curses', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Загрузить файл')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='sign_up_for_a_course',
            name='authors_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Служебный комментарий'),
        ),
    ]
