# Generated by Django 3.2.16 on 2024-04-18 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0013_auto_20240418_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
