# Generated by Django 3.2.16 on 2024-04-18 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0016_auto_20240419_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='link',
        ),
        migrations.AddField(
            model_name='video',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curses.link'),
        ),
    ]
