# Generated by Django 3.2.16 on 2024-04-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0019_auto_20240419_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_link',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.ManyToManyField(blank=True, null=True, to='curses.File_Link', verbose_name='Загрузить файл'),
        ),
    ]
