# Generated by Django 3.2.16 on 2024-04-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0020_auto_20240419_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Заголовок'),
        ),
    ]
