# Generated by Django 3.2.16 on 2024-04-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0021_link_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.DeleteModel(
            name='File_Link',
        ),
    ]
