# Generated by Django 3.2.16 on 2024-04-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0022_auto_20240419_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.ManyToManyField(blank=True, to='curses.Link', verbose_name='Ссылки'),
        ),
    ]
