# Generated by Django 3.2.16 on 2024-04-21 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_alter_trainer_options'),
        ('curses', '0023_auto_20240420_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='curse',
            name='link',
            field=models.ManyToManyField(blank=True, to='curses.Link', verbose_name='Ссылки'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainers', to='trainer.trainer', verbose_name='Тренер'),
        ),
    ]
