# Generated by Django 3.2.16 on 2024-04-16 14:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('surname', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('is_published', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть публикацию.', verbose_name='Опубликовано')),
                ('photo', models.ImageField(upload_to='images/trainer')),
            ],
            options={
                'verbose_name': 'тренир',
                'verbose_name_plural': 'Трениры',
            },
        ),
    ]
