# Generated by Django 3.2.16 on 2024-04-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_auto_20240417_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': 'тренeра', 'verbose_name_plural': 'Тренeры'},
        ),
    ]
