# Generated by Django 3.2.16 on 2024-04-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trash_File_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='Заголовок')),
                ('file', models.FileField(blank=True, null=True, upload_to='all_file', verbose_name='Загрузить файл')),
            ],
            options={
                'verbose_name': 'Загрузить файл',
                'verbose_name_plural': 'Загрузить файлы',
            },
        ),
    ]
