# Generated by Django 3.2.16 on 2024-04-06 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_title', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curse',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='site_title.trainer', verbose_name='Местоположение'),
        ),
    ]
