# Generated by Django 3.2.16 on 2024-04-06 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_title', '0002_curse_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curse',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainers', to='site_title.trainer', verbose_name='Тренир'),
        ),
    ]
