# Generated by Django 3.2.16 on 2024-04-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_title', '0003_alter_curse_trainer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
