# Generated by Django 3.2.16 on 2024-04-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_title', '0004_delete_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть публикацию.', verbose_name='Опубликовано'),
        ),
    ]
