# Generated by Django 3.2.16 on 2024-04-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_title', '0005_trainer_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=256, null=True, verbose_name='Адрес'),
        ),
    ]
