# Generated by Django 3.2.16 on 2024-04-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_memory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super_memory',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время конкурса'),
        ),
        migrations.AlterField(
            model_name='super_memory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='super_memory', verbose_name='photo'),
        ),
    ]
