# Generated by Django 3.2.16 on 2024-04-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_memory', '0003_remove_super_memory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super_memory',
            name='title',
            field=models.CharField(help_text='Данный заголовок преднозначен для личного понимания', max_length=256, verbose_name='Заголовок'),
        ),
    ]
