# Generated by Django 3.2.16 on 2024-04-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0024_auto_20240421_2208'),
        ('super_memory', '0004_alter_super_memory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='super_memory',
            name='link',
            field=models.ManyToManyField(blank=True, to='curses.Link', verbose_name='Ссылки'),
        ),
    ]
