# Generated by Django 3.2.16 on 2024-04-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_memory', '0006_remove_super_memory_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super_memory',
            name='photo',
            field=models.ImageField(blank=True, help_text='Форматы изображения jpg и png', null=True, upload_to='super_memory', verbose_name='photo'),
        ),
    ]
