# Generated by Django 3.2.16 on 2024-04-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': 'тренира', 'verbose_name_plural': 'Трениры'},
        ),
        migrations.AlterField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(upload_to='trainer'),
        ),
    ]
