# Generated by Django 3.2.16 on 2024-04-17 20:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_auto_20240416_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(upload_to='trainers'),
        ),
    ]
