# Generated by Django 3.2.16 on 2024-04-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_alter_trainer_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(help_text='Форматы изображения jpg и png', upload_to='trainers'),
        ),
    ]
