# Generated by Django 3.2.16 on 2024-04-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть публикацию.', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('author', models.CharField(blank=True, max_length=256, null=True, verbose_name='Автор публикации')),
                ('publishing_house', models.CharField(blank=True, max_length=256, null=True, verbose_name='Издательство')),
                ('the_year_of_publishing', models.CharField(max_length=256, null=True, verbose_name='год издания')),
                ('ISBN', models.CharField(blank=True, max_length=256, null=True, verbose_name='ISBN')),
                ('count_of_pages', models.IntegerField(verbose_name='Число страниц')),
                ('format', models.CharField(max_length=256, verbose_name='Формат')),
                ('circulation', models.CharField(max_length=256, verbose_name='Тираж')),
                ('link', models.URLField(help_text='Введите ссылку на скачивание', null=True, verbose_name='Ссылка на скачивание')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
