# Generated by Django 3.2.16 on 2024-04-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.URLField(blank=True, help_text='Введите ссылку на скачивание', null=True, verbose_name='Ссылка на скачивание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='book', verbose_name='photo'),
        ),
    ]
