# Generated by Django 3.2.16 on 2024-04-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20240417_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'книгу', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='book',
            name='circulation',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Тираж'),
        ),
        migrations.AlterField(
            model_name='book',
            name='count_of_pages',
            field=models.IntegerField(blank=True, null=True, verbose_name='Число страниц'),
        ),
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Формат'),
        ),
    ]
