# Generated by Django 3.2.16 on 2024-04-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20240419_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='the_year_of_publishing',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='год издания'),
        ),
    ]
