# Generated by Django 3.2.16 on 2024-04-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_the_year_of_publishing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, help_text='Форматы изображения jpg и png', null=True, upload_to='book', verbose_name='photo'),
        ),
    ]
